version: '3'

services:
  server:
    container_name: pr-server
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8100"
    ports:
      - "8100:8100"
    volumes:
      - ./:/app
    logging:
      driver: "json-file"
      options:
        max-size: "60m"
        max-file: "10"
    restart: on-failure
    networks:
      - pr-network
  
  db:
    container_name: pr-db
    shm_size: '1gb'
    build:
      context: .
      dockerfile: ./db.dockerfile
    expose:
      - "5432"
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: pr_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "123456"
    restart: unless-stopped
    networks:
      - pr-network

networks:
  pr-network:
    name: pr-network